apiVersion: v1
kind: Service
metadata:
  name: remix
  namespace: remix
  labels:
    app: remix
spec:
  type: ClusterIP
  selector:
    app: remix
  ports:
  - port: 80
    targetPort: 5173
    protocol: TCP
    name: http
