apiVersion: apps/v1
kind: Deployment
metadata:
  name: remix
  namespace: remix
  labels:
    app: remix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remix
  template:
    metadata:
      labels:
        app: remix
    spec:
      containers:
      - name: remix
        image: remix
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5173
          name: http
          protocol: TCP
      restartPolicy: Always
